#!/usr/bin/env bash

set -e

if ! command -v yaml-docs > /dev/null 2>&1; then
    echo "Please install yaml-docs to run the pre-commit hook! https://github.com/theEndBeta/yaml-docs#installation"
    exit 1
fi

yaml-docs "${@}"
